########## Testcase 0: Failed ##########
Expected Output: 
rehana 1
karan 3
murthy 2
rajiv 5
kalyani 4
rehana 1
murthy 2
karan 3
kalyani 4
rajiv 5

Your Output: 
rehana 1
karan 3
murthy 2
rajiv 5
kalyani 4
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
murthy 1
kiran 2
rajiv 3
kalyani 4
kumar 5

Your Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
All Rooms are reserved
murthy 1
kiran 2
rajiv 3
kalyani 4
kumar 5

Your Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
All Rooms are reserved
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
All Rooms are reserved
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5

Your Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
All Rooms are reserved
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
Added 2 more rooms
alekhya 6
manasa 7
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5
alekhya 6
manasa 7

Your Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
Added 2 more rooms
alekhya 6
manasa 7
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
kumar 5
murthy 1
kiran 2
kalyani 3
kumar 4
kumar 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
Added 5 more rooms
alekhya 6
manasa 4
kumar 5
karthik 7
manohar 8
swetha 9
reddy 10
murthy 1
kiran 2
kalyani 3
manasa 4
kumar 5
alekhya 6
karthik 7
manohar 8
swetha 9
reddy 10

Your Output: 
kiran 2
murthy 1
kumar 3
All Rooms are reserved
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 6: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
swathi 5
Added 2 more rooms
alekhya 6
manasa 4
kumar 7
murthy 1
kiran 2
kalyani 3
manasa 4
swathi 5
alekhya 6
kumar 7

Your Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

########## Testcase 7: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
kumar 5
murthy 1
kiran 2
kalyani 3
kumar 4
kumar 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
Added 5 more rooms
alekhya 6
manasa 4
kumar 5
karthik 7
manohar 8
swetha 9
reddy 10
murthy 1
kiran 2
kalyani 3
manasa 4
kumar 5
alekhya 6
karthik 7
manohar 8
swetha 9
reddy 10

Your Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
kumar 5
Traceback (most recent call last):
  File "reservation.py", line 67, in <module>
    main()
  File "reservation.py", line 63, in main
    display()
  File "reservation.py", line 46, in display
    print(key, value)
NameError: name 'key' is not defined
----------------------------------------

